version: '3.2'

services:
  s3bench:
    image: shonpaz123/s3bench
    command: --endpoint-url http://rook-ceph-rgw-my-store-rook-ceph.apps-crc.testing
             --access-key PX1VBN1W4N184FKJU6Z9
             --secret-key phrBrYDvSsIKdyhQEFBp3WeWxyk5C4xDPKZ0hjJj
             --bucket benchmarks
             --object-size 2MiB
             --num-objects 100
             --workload write
             --cleanup no
             --elastic-url http://elasticsearch:9200
    networks:
      - elk

